version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/go:1.20 # Go image
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod tidy
      - run:
          name: Run Tests
          command: go test ./...

  docker-build:
    docker:
      - image: docker:20.10.16 # Docker-enabled image
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t vulnerable-go-app:latest .

  wizcli_scan:
    working_directory: ~/app
    docker:
      - image: docker:20.10.16 # Use a Docker-enabled image for pulling and scanning
    steps:
      - setup_remote_docker # Enable Docker-in-Docker for image scanning
      - checkout
      - run:
          name: Download Wiz CLI
          command: |
            mkdir -p /wizcli
            curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64
            chmod +x ./wizcli
      - run:
          name: Authenticate to Wiz
          command: ./wizcli auth --id ${cromd7btaned7jpdpist4nqsp3c72kqq72cvreuwrgrzh24srmdgs} --secret ${agswrKs7fLfImAGKeRQDhsT9hEVu06yIMZFnysgz8NJvt0TxVfSU7x3EwgTiv9L9}
      - run:
          name: Scan Docker Image
          command: |
            docker pull vulnerable-go-app:latest
            ./wizcli docker scan --image vulnerable-go-app:latest --policy "Default vulnerabilities policy"

workflows:
  version: 2
  build-and-scan-workflow:
    jobs:
      - build-and-test
      - docker-build:
          requires:
            - build-and-test
      - wizcli_scan:
          requires:
            - docker-build
