version: 2.1

jobs:
  docker-build:
    docker:
      - image: docker:20.10.16
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t vulnerable-go-app:latest .
      - run:
          name: Save Docker Image as Tarball
          command: |
            mkdir -p /workspace
            docker save vulnerable-go-app:latest -o /workspace/vulnerable-go-app.tar
      - persist_to_workspace:
          root: /workspace
          paths:
            - vulnerable-go-app.tar

  wizcli_scan:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /workspace
      - run:
          name: Download Wiz CLI
          command: |
            sudo mkdir -p /wizcli
            sudo curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64
            sudo chmod +x ./wizcli
      - run:
          name: Load Docker Image from Tarball
          command: docker load -i /workspace/vulnerable-go-app.tar
      - run:
          name: Authenticate with Wiz
          command: WIZ_ENV=test ./wizcli auth --id "${WIZCLI_ID}" --secret "${WIZCLI_SECRET}"
      - run:
          name: Scan Docker Image
          command: ./wizcli docker scan --image vulnerable-go-app:latest --policy "Default vulnerabilities policy"

workflows:
  version: 2
  build-and-scan-workflow:
    jobs:
      - docker-build
      - wizcli_scan:
          requires:
            - docker-build

