version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/go:1.20 # Use the Go 1.20 image
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod tidy
      - run:
          name: Run Tests
          command: go test ./...

  docker-build:
    docker:
      - image: docker:20.10.16 # Docker-enabled image
    steps:
      - checkout
      - setup_remote_docker: # Enable Docker-in-Docker
          version: 20.10.16
      - run:
          name: Build Docker Image
          command: docker build -t vulnerable-go-app .

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      - docker-build:
          requires:
            - build-and-test

